### ISSUE TITLE
Rich Presence buttons not showing.

### ISSUE THREAD

**Issue by yaajme** [sajtii/ra_cli#3]
Hey!
I have this running, but the profile buttons that are mentioned the doco don't seem to work for me.
I can confirm that I set it using the flag as expected, and it has been reflected in the config file.

I cannot see any RA Profile button in the discord rich presence.
![image](https://github.com/user-attachments/assets/1e687c60-b63e-49ce-b739-c556dc269b06)
![image](https://github.com/user-attachments/assets/a5d042b4-ed0e-43d1-be1d-6cf6830d6b0d)

**Comment by geozin** [comment]
Hi, I have the same issue

**Comment by sajtii** [comment]
Hello! 
For some reason, you can’t see the buttons on your own profile. As I mentioned in the README, only others can see the buttons. If you have a second account you can check your profile from there, or ask one of your friends to take a screenshot.
